//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.28 at 07:26:36 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rushydro.ru/vniig/ias/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.rushydro.vniig.ias.webservice;
