-- Заполнение таблицы объекты мониторинга
insert into object_monitor VALUES (1, 'Плотина');

-- Заполнение таблицы видов сигналов
insert into signal_type VALUES (1, 'Аналоговый');
insert into signal_type VALUES (2, 'Цифровой');

-- Заполнение Заполнение таблицы измеряемых параметров
insert into measured_parameter VALUES (1, 'Температура воздуха', 0);
insert into measured_parameter VALUES (2, 'Линейные перемещения', 0);
insert into measured_parameter VALUES (3, 'Давление', 0);
insert into measured_parameter VALUES (4, 'Плановые смещения', 0);
insert into measured_parameter VALUES (5, 'Осадки сооружения', 0);
insert into measured_parameter VALUES (6, 'Расход', 0);

-- Заполнение таблицы датчиков
insert into sensor VALUES (1, 'ЩА-1', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (2, 'ЩА-2', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (3, 'ЩА-3', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (4, 'ЩА-4', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (5, 'ЩА-5', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (6, 'ЩА-6', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (7, 'ЩА-7', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (8, 'ЩА-8', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (9, 'ЩА-9', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (10, 'ЩА-10', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (11, 'ЩА-11', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (12, 'ЩА-12', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (13, 'ЩА-13', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (14, 'ЩА-14', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (15, 'ЩА-15', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (16, 'ЩА-16', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (17, 'ТВ-1', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (18, 'ТБ-1', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (19, 'ТВ-2', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (20, 'ТБ-2', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (21, 'ВП-16', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (22, 'ДО-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (23, 'ДО-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (24, 'ДО-3', 1, 'Цифровые', 1, true);
insert into sensor VALUES (25, 'ДО-4', 1, 'Цифровые', 1, true);
insert into sensor VALUES (26, 'ДО-5', 1, 'Цифровые', 1, true);
insert into sensor VALUES (27, 'ДО-6', 1, 'Цифровые', 1, true);
insert into sensor VALUES (28, 'ДОО-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (29, 'ДОО-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (30, 'ДОО-3', 1, 'Цифровые', 1, true);
insert into sensor VALUES (31, 'ОДГН-1-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (32, 'ОДГН-1-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (33, 'ОДГН-2-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (34, 'ОДГН-2-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (35, 'ОДГН-3-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (36, 'ОДГН-3-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (37, 'ОДГН-4-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (38, 'ОДГН-4-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (39, 'ОДГН-5-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (40, 'ОДГН-5-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (41, 'ОДГН-6-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (42, 'ОДГН-6-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (43, 'ВП-12', 1, 'Цифровые', 1, true);
insert into sensor VALUES (44, 'ВП-13', 1, 'Цифровые', 1, true);
insert into sensor VALUES (45, 'ВП-14', 1, 'Цифровые', 1, true);
insert into sensor VALUES (46, 'ВП-15', 1, 'Цифровые', 1, true);
insert into sensor VALUES (47, 'ВП-1', 1, 'Токовые', 1, true);
insert into sensor VALUES (48, 'ВП-2', 1, 'Токовые', 1, true);
insert into sensor VALUES (49, 'ВП-3', 1, 'Токовые', 1, true);
insert into sensor VALUES (50, 'ВП-4', 1, 'Токовые', 1, true);
insert into sensor VALUES (51, 'ВП-5', 1, 'Токовые', 1, true);
insert into sensor VALUES (52, 'ВП-6', 1, 'Токовые', 1, true);
insert into sensor VALUES (53, 'ВП-8', 1, 'Токовые', 1, true);
insert into sensor VALUES (54, 'ВП-9', 1, 'Токовые', 1, true);
insert into sensor VALUES (55, 'ВП-10', 1, 'Токовые', 1, true);
insert into sensor VALUES (56, 'ВП-11', 1, 'Токовые', 1, true);
insert into sensor VALUES (57, 'Пп-1', 1, 'Токовые', 1, true);
insert into sensor VALUES (58, 'Пп-2', 1, 'Токовые', 1, true);
insert into sensor VALUES (59, 'Пп-3', 1, 'Токовые', 1, true);
insert into sensor VALUES (60, 'Пп-4', 1, 'Токовые', 1, true);
insert into sensor VALUES (61, 'Пп-5', 1, 'Токовые', 1, true);
insert into sensor VALUES (62, 'Пп-6', 1, 'Токовые', 1, true);
insert into sensor VALUES (63, 'Пп-7', 1, 'Токовые', 1, true);
insert into sensor VALUES (64, 'Пп-8', 1, 'Токовые', 1, true);
insert into sensor VALUES (65, 'Пп-9', 1, 'Токовые', 1, true);



-- Заполнение таблицы сигналов
insert into signal VALUES (1, 1, 1, 2);
insert into signal VALUES (2, 2, 1, 2);
insert into signal VALUES (3, 3, 1, 2);
insert into signal VALUES (4, 4, 1, 2);
insert into signal VALUES (5, 5, 1, 2);
insert into signal VALUES (6, 6, 1, 2);
insert into signal VALUES (7, 7, 1, 2);
insert into signal VALUES (8, 8, 1, 2);
insert into signal VALUES (9, 9, 1, 2);
insert into signal VALUES (10, 10, 1, 2);
insert into signal VALUES (11, 11, 1, 2);
insert into signal VALUES (12, 12, 1, 2);
insert into signal VALUES (13, 13, 1, 2);
insert into signal VALUES (14, 14, 1, 2);
insert into signal VALUES (15, 15, 1, 2);
insert into signal VALUES (16, 16, 1, 2);
insert into signal VALUES (17, 17, 1, 1);
insert into signal VALUES (18, 18, 1, 1);
insert into signal VALUES (19, 19, 1, 1);
insert into signal VALUES (20, 20, 1, 1);
insert into signal VALUES (21, 21, 1, 3);
insert into signal VALUES (22, 22, 2, 4);
insert into signal VALUES (23, 23, 2, 4);
insert into signal VALUES (24, 24, 2, 4);
insert into signal VALUES (25, 25, 2, 4);
insert into signal VALUES (26, 26, 2, 4);
insert into signal VALUES (27, 27, 2, 4);
insert into signal VALUES (28, 28, 2, 4);
insert into signal VALUES (29, 29, 2, 4);
insert into signal VALUES (30, 30, 2, 4);
insert into signal VALUES (31, 31, 2, 5);
insert into signal VALUES (32, 32, 2, 5);
insert into signal VALUES (33, 33, 2, 5);
insert into signal VALUES (34, 34, 2, 5);
insert into signal VALUES (35, 35, 2, 5);
insert into signal VALUES (36, 36, 2, 5);
insert into signal VALUES (37, 37, 2, 5);
insert into signal VALUES (38, 38, 2, 5);
insert into signal VALUES (39, 39, 2, 5);
insert into signal VALUES (40, 40, 2, 5);
insert into signal VALUES (41, 41, 2, 5);
insert into signal VALUES (42, 42, 2, 5);
insert into signal VALUES (43, 43, 2, 6);
insert into signal VALUES (44, 44, 2, 6);
insert into signal VALUES (45, 45, 2, 6);
insert into signal VALUES (46, 46, 2, 6);
insert into signal VALUES (47, 47, 1, 6);
insert into signal VALUES (48, 48, 1, 6);
insert into signal VALUES (49, 49, 1, 6);
insert into signal VALUES (50, 50, 1, 6);
insert into signal VALUES (51, 51, 1, 6);
insert into signal VALUES (52, 52, 1, 6);
insert into signal VALUES (53, 53, 1, 6);
insert into signal VALUES (54, 54, 1, 6);
insert into signal VALUES (55, 55, 1, 6);
insert into signal VALUES (56, 56, 1, 6);
insert into signal VALUES (57, 57, 1, 3);
insert into signal VALUES (58, 58, 1, 3);
insert into signal VALUES (59, 59, 1, 3);
insert into signal VALUES (60, 60, 1, 3);
insert into signal VALUES (61, 61, 1, 3);
insert into signal VALUES (62, 62, 1, 3);
insert into signal VALUES (63, 63, 1, 3);
insert into signal VALUES (64, 64, 1, 3);
insert into signal VALUES (65, 65, 1, 3);