-- Заполнение таблицы объекты мониторинга
insert into object_monitor VALUES (1, 'Плотина');

-- Заполнение таблицы видов сигналов
insert into signal_type VALUES (1, 'Аналоговый');
insert into signal_type VALUES (2, 'Цифровой');

-- Заполнение Заполнение таблицы измеряемых параметров
insert into measured_parameter VALUES (1, 'Температура воздуха', 0);
insert into measured_parameter VALUES (2, 'Линейные перемещения', 0);
insert into measured_parameter VALUES (3, 'Давление', 0);
insert into measured_parameter VALUES (4, 'Плановые смещения', 0);
insert into measured_parameter VALUES (5, 'Осадки сооружения', 0);
insert into measured_parameter VALUES (6, 'Расход', 0);

-- Заполнение таблицы датчиков
insert into sensor VALUES (1, 'ЩА-1', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (2, 'ЩА-2', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (3, 'ЩА-3', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (4, 'ЩА-4', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (5, 'ЩА-5', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (6, 'ЩА-6', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (7, 'ЩА-7', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (8, 'ЩА-8', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (9, 'ЩА-9', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (10, 'Т-1', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (11, 'Т-2', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (12, 'Т-3', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (13, 'Т-4', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (14, 'Т-5', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (15, 'ТБ-1', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (16, 'ТБ-2', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (17, 'ТБ-3', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (18, 'П7-1-1', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (19, 'П7-1-2', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (20, 'П7-1-3', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (21, 'П7-1-4', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (22, 'П7-1-5', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (23, 'П7-1-6', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (24, 'П7-1-7', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (25, 'П7-1-8', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (26, 'П7-1-9', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (27, 'П7-1-10', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (28, 'П7-1-11', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (29, 'П7-1-12', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (30, 'П7-1-13', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (31, 'П7-1-14', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (32, 'П7-1-15', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (33, 'П7-1-16', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (34, 'П7-1-17', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (35, 'П7-1-18', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (36, 'П7-1-19', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (37, 'П7-1-20', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (38, 'П7-1-21', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (39, 'П7-1-22', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (40, 'П7-1-23', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (41, 'П7-1-24', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (42, 'П7-1-25', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (43, 'П7-1-26', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (44, 'П7-1-27', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (45, 'П7-1-28', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (46, 'П7-1-29', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (47, 'П7-1-30', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (48, 'П7-1-31', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (49, 'П7-1-32', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (50, 'П7-1-33', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (51, 'П7-1-34', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (52, 'П7-1-35', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (53, 'П7-1-36', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (54, 'П7-1-37', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (55, 'П7-1-38', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (56, 'П7-1-39', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (57, 'П7-1-40', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (58, 'П7-1-41', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (59, 'П7-1-42', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (60, 'П7-1-43', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (61, 'П7-1-44', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (62, 'П7-1-45', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (63, 'ДУНБ', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (64, 'ВП-10', 1, 'Волоконно-оптические', 1, true);
insert into sensor VALUES (65, 'ДО-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (66, 'ДО-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (67, 'ДО-3', 1, 'Цифровые', 1, true);
insert into sensor VALUES (68, 'ОДГН-1-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (69, 'ОДГН-1-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (70, 'ОДГН-1-3', 1, 'Цифровые', 1, true);
insert into sensor VALUES (71, 'ВП-1', 1, 'Цифровые', 1, true);
insert into sensor VALUES (72, 'ВП-2', 1, 'Цифровые', 1, true);
insert into sensor VALUES (73, 'ВП-3', 1, 'Цифровые', 1, true);
insert into sensor VALUES (74, 'ВП-4', 1, 'Цифровые', 1, true);
insert into sensor VALUES (75, 'ВП-5', 1, 'Цифровые', 1, true);
insert into sensor VALUES (76, 'ВП-6', 1, 'Цифровые', 1, true);
insert into sensor VALUES (77, 'ВП-7', 1, 'Цифровые', 1, true);
insert into sensor VALUES (78, 'ВП-8', 1, 'Цифровые', 1, true);
insert into sensor VALUES (79, 'ВП-9', 1, 'Цифровые', 1, true);

-- Заполнение таблицы сигналов
insert into signal VALUES (1, 1, 1, 2);
insert into signal VALUES (2, 2, 1, 2);
insert into signal VALUES (3, 3, 1, 2);
insert into signal VALUES (4, 4, 1, 2);
insert into signal VALUES (5, 5, 1, 2);
insert into signal VALUES (6, 6, 1, 2);
insert into signal VALUES (7, 7, 1, 2);
insert into signal VALUES (8, 8, 1, 2);
insert into signal VALUES (9, 9, 1, 2);
insert into signal VALUES (10, 10, 1, 1);
insert into signal VALUES (11, 11, 1, 1);
insert into signal VALUES (12, 12, 1, 1);
insert into signal VALUES (13, 13, 1, 1);
insert into signal VALUES (14, 14, 1, 1);
insert into signal VALUES (15, 15, 1, 1);
insert into signal VALUES (16, 16, 1, 1);
insert into signal VALUES (17, 17, 1, 1);
insert into signal VALUES (18, 18, 1, 3);
insert into signal VALUES (19, 19, 1, 3);
insert into signal VALUES (20, 20, 1, 3);
insert into signal VALUES (21, 21, 1, 3);
insert into signal VALUES (22, 22, 1, 3);
insert into signal VALUES (23, 23, 1, 3);
insert into signal VALUES (24, 24, 1, 3);
insert into signal VALUES (25, 25, 1, 3);
insert into signal VALUES (26, 26, 1, 3);
insert into signal VALUES (27, 27, 1, 3);
insert into signal VALUES (28, 28, 1, 3);
insert into signal VALUES (29, 29, 1, 3);
insert into signal VALUES (30, 30, 1, 3);
insert into signal VALUES (31, 31, 1, 3);
insert into signal VALUES (32, 32, 1, 3);
insert into signal VALUES (33, 33, 1, 3);
insert into signal VALUES (34, 34, 1, 3);
insert into signal VALUES (35, 35, 1, 3);
insert into signal VALUES (36, 36, 1, 3);
insert into signal VALUES (37, 37, 1, 3);
insert into signal VALUES (38, 38, 1, 3);
insert into signal VALUES (39, 39, 1, 3);
insert into signal VALUES (40, 40, 1, 3);
insert into signal VALUES (41, 41, 1, 3);
insert into signal VALUES (42, 42, 1, 3);
insert into signal VALUES (43, 43, 1, 3);
insert into signal VALUES (44, 44, 1, 3);
insert into signal VALUES (45, 45, 1, 3);
insert into signal VALUES (46, 46, 1, 3);
insert into signal VALUES (47, 47, 1, 3);
insert into signal VALUES (48, 48, 1, 3);
insert into signal VALUES (49, 49, 1, 3);
insert into signal VALUES (50, 50, 1, 3);
insert into signal VALUES (51, 51, 1, 3);
insert into signal VALUES (52, 52, 1, 3);
insert into signal VALUES (53, 53, 1, 3);
insert into signal VALUES (54, 54, 1, 3);
insert into signal VALUES (55, 55, 1, 3);
insert into signal VALUES (56, 56, 1, 3);
insert into signal VALUES (57, 57, 1, 3);
insert into signal VALUES (58, 58, 1, 3);
insert into signal VALUES (59, 59, 1, 3);
insert into signal VALUES (60, 60, 1, 3);
insert into signal VALUES (61, 61, 1, 3);
insert into signal VALUES (62, 62, 1, 3);
insert into signal VALUES (63, 63, 1, 3);
insert into signal VALUES (64, 64, 1, 3);
insert into signal VALUES (65, 65, 2, 4);
insert into signal VALUES (66, 66, 2, 4);
insert into signal VALUES (67, 67, 2, 4);
insert into signal VALUES (68, 68, 2, 5);
insert into signal VALUES (69, 69, 2, 5);
insert into signal VALUES (70, 70, 2, 5);
insert into signal VALUES (71, 71, 2, 6);
insert into signal VALUES (72, 72, 2, 6);
insert into signal VALUES (73, 73, 2, 6);
insert into signal VALUES (74, 74, 2, 6);
insert into signal VALUES (75, 75, 2, 6);
insert into signal VALUES (76, 76, 2, 6);
insert into signal VALUES (77, 77, 2, 6);
insert into signal VALUES (78, 78, 2, 6);
insert into signal VALUES (79, 79, 2, 6);